- name: install and start nginx
  hosts: frontend
  become: yes    # be for becomes sudo 
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service:   #systemctl start nginx 
      name: nginx
      state: started
      enabled: yes